# Generated by Django 3.0 on 2023-01-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO profiles_profile (
                user_id,
                favorite_city
            )
            SELECT
                user_id,
                favorite_city
            FROM
                oc_lettings_site_profile;
        """)
    ]
