version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: theya/cci-demo-docker-primary

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Initialize environement
          command: |
            python -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".env"
      - run:
          name: Run Lint
          command: |
            . env/bin/activate
            flake8
      - run:
          name: Run Tests
          command: |
            . env/bin/activate
            python manage.py test
  dockerize:
    executor: docker-publisher
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Dockerize
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker build -t $IMAGE_NAME .
            docker tag $IMAGE_NAME "${IMAGE_NAME}:${CIRCLE_SHA1}"
            docker push "${IMAGE_NAME}:${CIRCLE_SHA1}"

workflows:
  main:
    jobs:
      - build-and-test
      - dockerize:
          context: Openclassrooms
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
