version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: theya/cci-demo-docker-primary

jobs:
  test:
    docker:
      - image: theya/cci-demo-docker-primary:0.0.1
    steps:
      - checkout
      - run:
          name: "Tests"
          command: "python manage.py test"
  lint:
    docker:
      - image: theya/cci-demo-docker-primary:0.0.1
    steps:
      - checkout
      - run:
          name: "Lint"
          command: "flake8"
  dockerize:
    executor: docker-publisher
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Test"
          command: echo $DOCKERHUB_PASSWORD & echo $DOCKERHUB_USERNAME
      - run:
          name: "Build"
          command: "docker build . -t $IMAGE_NAME"
      - deploy:
          name: "Push application Docker image"
          command: |
            if [ "${CIRCLE_BRANCH}" == "tests" ]; then
              echo $DOCKERHUB_PASSWORD | docker login -u "$DOCKERHUB_USERNAME" —p "$DOCKERHUB_PASSWORD"
              docker tag $IMAGE_NAME "${ECR_ENDPOINT}/cci-demo-docker-primary:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/cci-demo-docker-primary:${CIRCLE_SHA1}"
            fi

workflows:
  workflow:
    jobs:
      - lint
      - test
      - dockerize:
          context: Openclassrooms
