# Generated by Django 3.0 on 2023-01-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20230110_1118'),
        ('profiles', '0002_auto_20230110_1118'),
        ('lettings', '0002_auto_20230110_1124')
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
